/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE linkBaseService PLEASE EDIT ../link.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Link } from '../../domain/sito_pa_db/link';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Link.service.ts
 */

/*
 * SCHEMA DB Link
 *
	{
		link: {
			type: 'String'
		},
		link_desc: {
			type: 'String'
		},
		link_order: {
			type: 'Number'
		},
		link_type: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class LinkBaseService {

    contextUrl: string = environment.endpoint + '/links';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * LinkService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Link): Observable<Link> {
        return this.http
            .post<Link>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * LinkService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * LinkService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Link> {
        return this.http
            .get<Link>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * LinkService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Link[]> {
        return this.http
            .get<Link[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * LinkService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Link): Observable<Link> {
        return this.http
            .post<Link>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
